### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#1]
_Elvin, reponuzu ümumi analiz etdim və yanlış olduğunu fikirləşdiyim bəzi məqamlar var. Məsələn, [commit mesajları](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali/) düzgün deyil və ".md" uzantılı faylların sonunda ".txt" yazılmalı deyil. 2 branch var, birini lazım deyilsə silin, məncə. Css faylları "css" adlı qovluqda olmalıdır, şəkillər isə "img" adlı qovluqda ola bilər, yəni mütləq başqa bir qovluqda olmalıdır. Bəzi şəkil adları düzgün deyil, şəkil adlarında boşluq olmalı deyil və şəklin özünə uyğun ad qoyulmalıdır. Daha çox px yox, em və rem kimi ölçü vahidlərindən istifadə edilsə əla olar (responsivlikdə də kömək olar). Çalışın işlərinizi gündəlik olaraq GitHuba push edin. Uğurlar!🙂_

**Comment by ElvinMemmedov** [comment]
Salam twk koney ede bilersiz duzeldim sI qeyde aldiginiz sehfleri

пн, 22 нояб. 2021 г., 12:02 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Salam. Mentorunuzdan kömək istəyə bilərsiniz, amma birinci özünüz etməyə çalışın. Yuxarıda "commit mesajları" sözünün üstünə basanda həmin mövzu ilə bağlı link gəlir, onu da oxuya bilərsiniz.

**Comment by ElvinMemmedov** [comment]
Bu adlari mentorlar deyib yazmiwam ozum fikirlewib yazmamiwam

вт, 30 нояб. 2021 г., 21:14 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Hansı adları?

**Comment by ElvinMemmedov** [comment]
Txt md

вт, 30 нояб. 2021 г., 22:49 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Hə, qovluğun içi boş qalmasın deyə demiş ola bilərlər. Boş olanda bura düşmür, görünmür, yəni.

**Comment by isbendiyarovanezrin** [comment]
Bu cür yazılış səhvdir.

**Comment by isbendiyarovanezrin** [comment]
Fayl adları "README.md" və "Research.md" şəklində olmalıdır.

**Comment by ElvinMemmedov** [comment]
Cox saq olun a deyiwe bilmedim adlarin

вт, 30 нояб. 2021 г., 23:05 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Sizin mentorunuz kimdir?

**Comment by ElvinMemmedov** [comment]
Aide

вт, 30 нояб. 2021 г., 23:11 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by ElvinMemmedov** [comment]
Bir nece defe komeyliy etdi bezi movzularda soradan komeyliy lazim oldu bir
nece defe yazdim cvb vermedi yeni cvb gelmedi

вт, 30 нояб. 2021 г., 23:13 elvin memmedov ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Yaxşı, deyəcəm kömək etsin sizə.

**Comment by ElvinMemmedov** [comment]
Ehtiyac yoxdu. siz cox saq olun .men bir nece defe yazmiwam baxib cvb
vermeyib

вт, 30 нояб. 2021 г., 23:15 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Aidə kursu dayandırıb, indi xəbərim oldu.

**Comment by ElvinMemmedov** [comment]
Bawa duwdum twk

вт, 30 нояб. 2021 г., 23:19 Nəzrin İsbəndiyarova ***@***.***>:
