### ISSUE TITLE
Bu testi işləyin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#11]
25 sualdan ibarət **[bu](https://www.w3schools.com/js/js_quiz.asp)** JavaScript testini işləyə bilərsiniz. Belə testlər işləmək JavaScript haqqında nə qədər bildiyinizi və ya bilmədiyinizi öyrənmək üçün yaxşı yoldur.

**Comment by ElvinMemmedov** [comment]
Testi iwledim 78 % oldu

пт, 17 дек. 2021 г., 21:08 Nəzrin İsbəndiyarova ***@***.***>:
