### ISSUE TITLE
Reponu update edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#13]
Repo hər gün update olunmalıdır.

**Comment by ElvinMemmedov** [comment]
cox saq olun.mende update problem var yeni master main.

**Comment by ElvinMemmedov** [comment]
nece duzelde bilerik?

**Comment by isbendiyarovanezrin** [comment]
@Mehemmed0330

**Comment by ElvinMemmedov** [comment]
Her muraaciet edende komeynen bagli her defede ofise gel orda hell edek
deyir men ofise gele bilseydim ele muellimnen hell ederdim

пт, 17 дек. 2021 г., 23:17 Nəzrin İsbəndiyarova ***@***.***>:
