### ISSUE TITLE
CSS faylları "css" adlı qovluqda olmalıdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#16]
Məsələn, **[bu](https://github.com/ElvinMemmedov/PragmatechFoundatoinProject/tree/main/works/rentacar)** hissədə səhv yazmısınız.

**Comment by ElvinMemmedov** [comment]
Salam cox saq olun .updade epemeyde problem var onu hell ede bilmiren

вс, 19 дек. 2021 г., 21:20 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Məhəmməd baxır o işlərə, mən yox.

**Comment by ElvinMemmedov** [comment]
Bawa duwdum twk

вс, 19 дек. 2021 г., 21:52 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by ElvinMemmedov** [comment]
Nezrin xanim c dilini bilirsiz yeni melumatiniz var?

вс, 19 дек. 2021 г., 21:55 elvin memmedov ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Xeyr, bilmirəm. :)

**Comment by ElvinMemmedov** [comment]
Bu hissede ne sehv yazilib

вс, 19 дек. 2021 г., 21:20 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Hansı?

**Comment by ElvinMemmedov** [comment]
Bu hissede

вс, 19 дек. 2021 г., 21:20 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Başlıqda yazmışam. CSS faylları "css" adlı qovluqda olmalıdır.

**Comment by ElvinMemmedov** [comment]
Bulari githubda duzeltmeliyem yoxsa papkada ?

вс, 19 дек. 2021 г., 22:15 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
GitHubda etmək olmur, məncə.

**Comment by ElvinMemmedov** [comment]
Oldu twk

вс, 19 дек. 2021 г., 22:06 Nəzrin İsbəndiyarova ***@***.***>:
