### ISSUE TITLE
Slider yaza bilmək üçün qaynaqlar

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#22]
_Bu nümunələri analiz edin._

- **[1-ci qaynaq](https://freefrontend.com/css-sliders)**
- **[2-ci qaynaq](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_slideshow)**
- **[3-cü qaynaq](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_slideshow_auto)**
- **[4-cü qaynaq](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_slideshow_multiple)**
- **[5-ci qaynaq](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_slideshow_gallery)**

**Comment by ElvinMemmedov** [comment]
Cox saq olun

пн, 20 дек. 2021 г., 20:21 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by ElvinMemmedov** [comment]
Ingilis dilinde bawa duwmek cetindi bir az bawqa dilde varmi

пн, 20 дек. 2021 г., 20:21 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Əsas kodlardır, kodlara baxın.

**Comment by ElvinMemmedov** [comment]
Tamam oldu

пн, 20 дек. 2021 г., 20:31 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Xeyr, türk və bizim dildə mövzu ilə bağlı yaxşı qaynaqlar yoxdur. Mən tapmadım.
