### ISSUE TITLE
Repo adını səhv yazmısınız

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#24]
"Foundatoin" yox "Foundation" yazılmalıdır.

**Comment by ElvinMemmedov** [comment]
Deyiwe bilmirem .onu githubdan yoxsa fayldan?

пн, 20 дек. 2021 г., 21:17 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by ElvinMemmedov** [comment]
Tamamdi deyiwdim

пн, 20 дек. 2021 г., 21:17 Nəzrin İsbəndiyarova ***@***.***>:
