### ISSUE TITLE
JavaScriptdən bu məsələləri işləməyə çalışın

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#25]
**[Bu](https://www.w3resource.com/javascript-exercises/javascript-basic-exercises.php)** linkdə 150 dənə çox da çətin olmayan Javascript məsələləri var. Boş vaxtlarınızda işləyə bilərsiniz.

**Comment by ElvinMemmedov** [comment]
Nezrin xanim men funksiyalari bilmirem yeni hec bawa duwmurem onu
oyrenmek.istiyirem

пн, 20 дек. 2021 г., 21:57 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Bununla bağlı issue yazdım.
