### ISSUE TITLE
JavaScript funksiyaları öyrənmək üçün qaynaqlar

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#26]
- **[1-ci qaynaq](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions)**
- **[2-ci qaynaq](https://www.w3schools.com/js/js_functions.asp)**
- **[3-cü qaynaq](https://youtu.be/je0ZyT0PuQ0)**
- **[4-cü qaynaq](https://youtu.be/HNqoXSQCDZk)**
- **[5-ci qaynaq](https://youtu.be/KO8aZFwtVwY)**

**Comment by ElvinMemmedov** [comment]
Cox saq olun

пн, 20 дек. 2021 г., 22:18 Nəzrin İsbəndiyarova ***@***.***>:
