### ISSUE TITLE
GitHubda aktiv olun

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#3]
Aylardır GitHuba heç nə əlavə etməmisiniz. 1 sətir kod belə yazsanız GitHuba əlavə edin. Bu çox vacibdir. Əlavə edin ki, baxıb səhvlərinizi deyə bilək.

**Comment by isbendiyarovanezrin** [comment]
Master branch'ında belə imiş. Main branch'ında 23 gün əvvəl update olunub, amma hər gün olunmalıdır. Hər gün.

**Comment by ElvinMemmedov** [comment]
Salam.ne update eliyim?evvel lapiye sayt ustunde kodlar yazirdim oda heleki
yatimciq qalib.javacp oyrenmeye caliwiram oda zeif bawa duwurem deye hecne
update eliye bilmirem

сб, 11 дек. 2021 г., 01:20 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
Nə update edim? Təbii ki, nə yazmısınızsa onu. Səhv və ya düz. Biz hamımız proqramistliyi öyrənməyə çalışırıq və bu ancaq düz yazdığımızı düşündüyümüz kodları GitHuba yükləməklə olacaq iş deyil. Günün sonunda yazdığınız hər şeyi atın bura, baxıb səhvlərinizi desin Məhəmməd (mentorunuz). Nə sual olsa mənim əvvəl açdığım issue'nin altına yazın. Ən adi sualları belə.
