### ISSUE TITLE
CSS box-shadow

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#31]
:link:[**CSS box-shadow nümunələri**](https://getcssscan.com/css-box-shadow-examples)

_Portfolio saytınızda istifadə edə bilərsiniz._

**Comment by ElvinMemmedov** [comment]
Cox saq olun

пт, 24 дек. 2021 г., 22:51 Nəzrin İsbəndiyarova ***@***.***>:
