### ISSUE TITLE
2 branch var, birini lazım deyilsə silin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#8]
2 branch var, birini lazım deyilsə silin, məncə. Təxminən hər ikisində də eyni kodlar var.

**Comment by ElvinMemmedov** [comment]
Silmeye cehd eledim sile bilmedim

сб, 11 дек. 2021 г., 01:42 Nəzrin İsbəndiyarova ***@***.***>:

**Comment by isbendiyarovanezrin** [comment]
@Mehemmed0330, kömək et.
