### ISSUE TITLE
"CoderCrunch" saytından test işləyərək özünüzü yoxlayın

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [ElvinMemmedov/PragmatechFoundationProject#9]
[**CoderCrunch**](https://www.codercrunch.com/quiz/search?skill=javascript) saytından istədiyiniz dilə uyğun (sol tərəfdən seçmək olur) test işləyə bilərsiniz. Sonda da nəticənizi göstərir (neçə düz, neçə səhv etdiyinizi). Sizin üçün maraqlı ola biləcəyini düşündüm. İşləyib özünüzü istənilən dildə yoxlaya bilərsiniz.

**Comment by ElvinMemmedov** [comment]
oldu cox saq olun.js mene heleki cetin gelir nece oyrene bilerem bawa duwe bilerem

**Comment by isbendiyarovanezrin** [comment]
İndi sizə möhtəşəm bir siyahı atacam (issue şəklində). Mütləq baxın.

**Comment by ElvinMemmedov** [comment]
oldu cox saq olun oyrenib bawa duwe bilsem sizin eziyyetinizden cixacam)

**Comment by isbendiyarovanezrin** [comment]
Əziyyət verirəm? Sonuncu cümləni başa düşmədim.😕

**Comment by ElvinMemmedov** [comment]
xeyr.men size eziyyet verdim.oyrene bilsem bu qaynaqlarnan size borclu olaram

**Comment by isbendiyarovanezrin** [comment]
İnanıram, öyrənəcəksiniz.

**Comment by ElvinMemmedov** [comment]
insAllah.siz yenede vaxtiniz olduqca komey edin maraqlanin.geri qalmiwam qrupdan

**Comment by isbendiyarovanezrin** [comment]
Kursa gəlib məşğul ola bilərsiniz.

**Comment by isbendiyarovanezrin** [comment]
Orada hər an kömək etməyə kimsə olur.
